strict-sigcheck = false






[Instagram]
brand = "piko"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"


[Instagram.patches]
"github:crimera/piko" = { version = "dev" }
