name: Upload APKs to Telegram

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built APKs from release
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ github.repository }}
          latest: true
          fileName: "*.apk"
          out-file-path: "./apks"
        continue-on-error: true

      - name: Send APKs to Telegram
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TG_TOKEN }}
          to: ${{ secrets.TG_CHAT }}
          message: |
            🚀 **نئی بلڈ ریلیز ہو گئی!**
            ریپوزٹری: ${{ github.repository }}
            ٹیگ: ${{ github.event.release.tag_name || 'Latest Release' }}
          media: |
            ./apks/*.apk
          media-type: "document"
        continue-on-error: true
